### PR TITLE
Show user error notification, if user authorization agent not found

### LINKED ISSUE #394: Display error if the user has no Authorization Agent
Currently the `useRegisterApp` hook fail silently if the user has no Authorization Agent:

https://github.com/activitypods/activitypods/blob/9dbe64104610ede370e11822defb02177b2952c9/app-framework/react/src/hooks/useRegisterApp.ts#L16-L33

We should throw an error, and catch it here:

https://github.com/activitypods/activitypods/blob/9dbe64104610ede370e11822defb02177b2952c9/app-framework/react/src/components/LoginPage.tsx#L76-L78

Then use the `notify` function to display an error notification.

### PR DESCRIPTION
**Pull request by lxa4096**
Hello everyone,
this is my first contribution here :)

I tested it locally and it showed me the error notification, after I removed the interop:hasAuthorizationAgent triple from the dataset manually in my local setup. 
The relevant translation strings seem to be maintained in another project (semapps/auth-provider), where I will link the according PR here.

closes #394

### CODE REVIEW

**Comment by lxa4096** [comment]
Relevant message translation in semapps: https://github.com/assemblee-virtuelle/semapps/pull/1370

File: app-framework/react/src/components/LoginPage.tsx [hunk 1]
```diff
@@ -73,15 +73,19 @@ const LoginPage: FunctionComponent<Props> = ({ text, clientId, customPodProvider
...
-        registerApp(clientId, payload?.webid).then(appRegistrationUri => {
-          if (appRegistrationUri) setIsRegistered(true);
-        });
+        registerApp(clientId, payload?.webid)
+          .then(appRegistrationUri => {
+            if (appRegistrationUri) setIsRegistered(true);
+          })
+          .catch(error => {
+            notify('auth.message.user_authorization_agent_not_found', { type: 'error' });
+          });
```
Comment (srosset81) [inline app-framework/react/src/components/LoginPage.tsx:82]: This code means that **any** error will result in "User authorization agent not found". This can be confusing. I would suggest to instead throw the error with the translation key (in the useRegisterApp hook) and then render `error.message` here.

**Review by srosset81 — CHANGES_REQUESTED** [review]
Thanks a lot Alexej for your first contribution !
Since the LoginPage and useRegisterApp hooks are specific to the @activitypods/react package, you could please add the translation key [here](https://github.com/activitypods/activitypods/blob/master/app-framework/react/src/messages/en.ts) instead of in the @semapps/auth-provider package ?
Thanks !

File: app-framework/react/src/components/LoginPage.tsx (hunk 1 above)
Comment (lxa4096) [reply app-framework/react/src/components/LoginPage.tsx]: 👍

**Comment by lxa4096** [comment]
Sure, I pushed both changes again. 
I have seen above, that a translation key from semapps is referenced related to pod providers (auth.message.pod_providers_not_loaded) and thought this would be similar handled, but I put it in activitypods/react now.

**Review by srosset81 — APPROVED** [review]
Great job, thank you :-)
Let us know (maybe on the Matrix channel) if there are other issues you'd like to work on.
